In [ ]:
## 00.Pytorch Fundamentals

# Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

# If you have a question: https://githup.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print (torch.__version__)

2.6.0+cu124


## Introduction to Tensors
### Creating tensors

PyTorch tensors are created using "torch.tensor()" - https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Number of dimension of above scalar
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()


7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
#Dimension of above vector
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
matrix = torch.tensor([[7, 8],
                       [9, 10]])

matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# TENSOR with 3 '[' at begining and 3 ']' at end

TENSOR =torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# 3 '[' and 3 ']' at begining and end respectively indicates 3 dimension
TENSOR.ndim

3

In [ ]:
# The output means there's 1 dimension of 3 by 3.
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# TENSOR1
TENSOR1 = torch.tensor([[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]])
TENSOR1

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR1.ndim

2

In [ ]:
TENSOR1.shape

torch.Size([3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][2]

tensor([2, 4, 5])

In [ ]:
TENSOR1[2]

tensor([2, 4, 5])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that with tensors full of random numbers and then adjust those random numbers to better represent the data.

```Start with random numbers -> lokk at data -> update random numbers -> look at data -> update random numbers```

Torch random numbers: https://pytorch.org/docs/main/generated/torch.rand.html

In [ ]:
# Create a random tensor of size() (or shape) (3, 4). Note size() is a function and shape is attribute
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8481, 0.2068, 0.0425, 0.4092],
        [0.3085, 0.7892, 0.2597, 0.3317],
        [0.7343, 0.8404, 0.4320, 0.9342]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor of size (1, 3, 4)
random_tensor1 = torch.rand(1, 3, 4)
random_tensor1

tensor([[[0.9128, 0.4730, 0.3127, 0.9212],
         [0.7238, 0.7579, 0.9684, 0.1547],
         [0.4275, 0.0134, 0.7104, 0.4061]]])

In [ ]:
random_tensor1.ndim

3

In [ ]:
# Create a random tensor of size (2, 3, 4)
random_tensor2 = torch.rand(2, 3, 4)
random_tensor2

tensor([[[0.0885, 0.4341, 0.4200, 0.3443],
         [0.7212, 0.3161, 0.6321, 0.6734],
         [0.8386, 0.2037, 0.7976, 0.0492]],

        [[0.9735, 0.1826, 0.6036, 0.7486],
         [0.6126, 0.9303, 0.0446, 0.1987],
         [0.1681, 0.2673, 0.6246, 0.6358]]])

In [ ]:
random_tensor2.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # Height, Width, Color channel (Red, Blue, Green)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# torch.rand(size=(3, 3)) is same as torch.rand(3, 3)
torch.rand(size=(3, 3))

tensor([[0.2160, 0.5096, 0.0723],
        [0.7295, 0.2818, 0.5927],
        [0.8367, 0.9939, 0.9270]])

In [ ]:
torch.rand(3, 3)

tensor([[0.3046, 0.5265, 0.8554],
        [0.2968, 0.7824, 0.3198],
        [0.5093, 0.0062, 0.6339]])

# Zeros and Ones tensor

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Multiply one tensor with zeros
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensors of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Data type of a tensor
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
# Use torch.arrange(). torch.range() deprecated.
one2ten = torch.arange(1, 11)
one2ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Another way of creating tensor range. See documention of torch.arange
tensor_range = torch.arange(start=0, end=1000, step=77)
tensor_range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating range of tensor-like
ten_zeros = torch.zeros_like(input=one2ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data type: https://pytorch.org/docs/stable/tensors.html
**Note**: Tensor data types is one of the 3 big error we'll run into with PyTorch and deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

### Float 32 Tensor

In [ ]:
float_32_tensor  = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# Though we mention data type as "None", the default data type float32
float_32_tensor.dtype

torch.float32

In [ ]:
# Create tensor for int data type
int_tensor  = torch.tensor([3.0, 6.0, 9.0],
                                dtype=int)
int_tensor

tensor([3, 6, 9])

In [ ]:
int_tensor.dtype

torch.int64

In [ ]:
float_32_tensor_1 = torch.tensor([3.0, 6.0, 9.0],
                                 dtype=None,  # What datatype is tensor, default value is float32
                                 device=None, # What device the tensor is on. It can be "cpu" or "cuda". cuda for GPU
                                 requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor_1

tensor([3., 6., 9.])

In [ ]:
float_32_tensor_1.dtype

torch.float32

In [ ]:
# convert float32 tensor to float16
float_16_tensor = float_32_tensor_1.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor_1

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor_1 * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors using tensor attributes
  1. Tensors not right datatype - to get datatype from a tensor, use: **tensor.dtype**
  2. Tensors not right shape - to get shape from a tensor, use **tensor.shape**
  3. Tensors not on the right device - to get device from a tensor use **tensor.device**


In [ ]:
# Create a tensor to demonstrate above
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3715, 0.0882, 0.1406, 0.0854],
        [0.4508, 0.4052, 0.1355, 0.3594],
        [0.5399, 0.6562, 0.8906, 0.0401]])

In [ ]:
# Find out details about the above tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3715, 0.0882, 0.1406, 0.0854],
        [0.4508, 0.4052, 0.1355, 0.3594],
        [0.5399, 0.6562, 0.8906, 0.0401]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)
Tensor operations include:
* Addtion
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor_add = tensor + 10
tensor_add

tensor([11, 12, 13])

In [ ]:
# Multiply tensor with 10
tensor_mul = tensor * 10
tensor_mul


tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor_sub = tensor -10
tensor_sub

tensor([-9, -8, -7])

In [ ]:
# Try PyTorch Multiplication function
tensor_mul1 = torch.mul(tensor, 10)
tensor_mul1

tensor([10, 20, 30])

In [ ]:
# Try PytOrch add function
tensor_add1 = torch.add(tensor, 10)
tensor_add1

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

Info about multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There two main rules that performing matrix muktiplication needs to be satisfied:
  1. The **inner dimension** must match:
    * `(3, 2) @ (3, 2)` won't work   Note: @ is same as tensor.matmul()
    Example: torch.matmul(torch.rand(3, 2), torch.rand(3, 2) won't work
    * `(2, 3) @ (3, 2)` will work
    * `(3, 2) @ (2, 3)` will work

  2. The resulting matrix has the shape of the **outer dimension** of input matrix:
    * `(2, 3) @ (3, 2) -> (2, 2)`
    * `(3, 2) @ (2, 3) -> (3, 3)`




In [ ]:
# Inner dimension does not match - Hence error
# torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

# Inner dimension match
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6702, 0.7419],
        [0.3762, 0.4689]])

In [ ]:
# Dimension of resulting matrix would be outer dimension of input matrices
torch.matmul(torch.rand(4, 3), torch.rand(3, 5))

tensor([[0.6979, 0.6540, 0.9722, 0.7626, 1.1536],
        [0.6785, 0.7267, 1.0960, 0.8101, 1.1961],
        [0.3468, 0.6287, 0.6891, 0.4920, 0.7127],
        [0.6889, 0.9967, 1.4026, 0.9634, 1.3752]])

In [ ]:
# Dimension of resulting matrix would be outer dimension of input matrices
torch.matmul(torch.rand(4, 3), torch.rand(3, 5)).shape

torch.Size([4, 5])

In [ ]:
# 1. Elelment-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# 2. Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3
# 2:25:04

14

In [ ]:
# Time to execute
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 859 µs, sys: 146 µs, total: 1.01 ms
Wall time: 1.11 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 53 µs, sys: 9 µs, total: 62 µs
Wall time: 66.3 µs


tensor(14)

** One of the most common errors in deep learning: shape error

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# Multiply matrix. Note: torch.mm() is an alias of torch.matmul()
torch.mm(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### To fix our tensor shape issues, we can manipulate the shape of one of tensors using **transpose**
###A **transpose** switch the axes of dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# Transpose tensor_B
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


#### **Finding the min, maxx, mean, sum, etc (tensor aggregation)**

In [ ]:
# Create a tensor
aggr = torch.arange(0, 100, 10)
aggr, aggr.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(aggr), aggr.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(aggr), aggr.max()

(tensor(90), tensor(90))

In [ ]:
# Find mean. data type of aggr is int64 as shown above. To compute mean, we need to convert to float32
# torch.mean(aggr) will cause error due to datatype mismatch
torch.mean(aggr.type(torch.float32)), aggr.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find sum
torch.sum(aggr), aggr.sum()

(tensor(450), tensor(450))

### Find the index of min and max value

In [ ]:
# Find the index of min value
aggr.argmin()

tensor(0)

In [ ]:
# Value at index 0
aggr[0]

tensor(0)

In [ ]:
# Find the index of the max value
aggr.argmax()

tensor(9)

In [ ]:
# Value at index 9
aggr[9]

tensor(90)

## Reshaping, stacking, squeezing and Unsqueezing tensors

* Reshaping - Reshapes an input to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (torch.vstack) or side by side (torch.hstack)
* Sqeeze - Removes all `1` dimensions from a tensor
* Unsqeeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (Swapped) in a certain way

In [ ]:
# Lets create a tensor to demonstrate above
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension. Understanding of reshape:
# x.reshape(N, R, C), Reshape to: N = Number of reshaped matrices, R = Row of each reshaped matrix, C = Column of each reshaped matrix
# Number of elements (N * R * C) of the reshaped tensor has to be same as the number of elements of original tensor
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape  # Note in the output that an extra [] is added to tensor x

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_reshaped1 = x.reshape(9, 1)
x_reshaped1, x_reshaped1.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
# change element at index 0 to 5
z[:, 0] = 5
z, x, x.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)  # try with different dim value eg. dim=1
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked1 = torch.stack([x, x, x, x], dim=1)
x_stacked1

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - Removes all single dimensions from a target tensor
# x_reshaped, x_reshaped.shape
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
x_reshaped, x_reshaped.squeeze()  # Note the output that one [] will be removed from x_reshaped when squeezed is called

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Check size
x_reshaped.shape, x_reshaped.squeeze().shape

(torch.Size([1, 9]), torch.Size([9]))

In [ ]:
# torch.unsqueeze() - Addes a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)  # try with dim=0
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute() - Rearrange the dimensions of a target of a target tensor in specified order
x_original = torch.rand(size=(224, 224, 3))  # [height (dim=0), width (dim=1), color_channels(dim=2)]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # Shifts axis/dim 0 (val=224) -> 1, 1(val=224) -> 2, 2(val=3) -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
# Show Original value. Why the same value - because permute use same memeory location as original torch. See doc by googling torch.permute
x_original[1, 1, 1], x_permuted[1, 1, 1]

(tensor(0.2240), tensor(0.2240))

In [ ]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (Selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Start with creating new tensor
import torch
x = torch.arange(1, 10)
y = x.reshape(1, 3, 3) # Or torch.reshape(x, (1, 3, 3))
x, y, x.shape, y.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([9]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor y
y[0] # i.e. first bracket '['

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on 2nd/middle bracket '[' (dim=1)
y[0][0] # y[0, 0] is same as y[0][0]

tensor([1, 2, 3])

In [ ]:
# Index on the most inner (third) bracket (last dimension, dim = 2)
y[0][0][0], y[0][0][2], y[0][2][0]

(tensor(1), tensor(3), tensor(7))

In [ ]:
# Use ":" to select "all" of a target dimension
y[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
y[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
y[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of the 0th and 1st dimension and all values of 2nd diemnsion
y[0, 0 ,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
y[0, 2, 2]

tensor(9)

In [ ]:
# Index on y to return 3, 6, 9
y[0,:,2] # or y[:, :, 2]

tensor([3, 6, 9])

### Pytorch tensors and NumPy

NumPy is popular scientific Python numerical computing Library. And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in Pytorch tensor -> torch.from_numpy(ndarray)
* Pytorch tensor to NumPy -> torch.tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # Warning: When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor
#

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Default data type tensor is float32, default datat type of NumPy is float64. When we convert NumPy to tensor whose data type be float64 (same as NumPy)
array.dtype, tensor.dtype, torch.arange(1.0, 8.0).dtype

(dtype('float64'), torch.float64, torch.float32)

In [ ]:
# Change the value of array and check whether tensor value changes
array = array + 1 # Add 1 to each item in array
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.dtype, tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'),
 torch.float32)

In [ ]:
# Change the tensor, what happens to `numpy_tensor'
tensor = tensor + 1 # Add 1 to each item of the tensor
tensor, numpy_tensor
#

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (Trying to take random out of random)

In short how a neural network learns:

Start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again ...

To reduce the randomness is neural networks and pytorch comes the concept of a random seed.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensor
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8050, 0.0295, 0.2627, 0.0974],
        [0.0476, 0.9821, 0.0817, 0.7457],
        [0.5149, 0.2331, 0.8471, 0.0350]])
tensor([[0.2322, 0.9389, 0.3539, 0.2681],
        [0.3127, 0.9331, 0.2516, 0.7882],
        [0.9167, 0.8486, 0.6258, 0.2248]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproduible tensors using random seed
# https://pytorch.org/docs/stable/notes/randomness.html
#

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Every time call torch.manual_seed() before calling torch.rand() to make the tensors equal to each other. Without this call tensors will not be equal
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(i.e. good)

1. Getting a GPU
  1. Easiest - Use google Colab for a free GPU (Options to upgrade as well)
  2. Use your own GPU - Takes a littlebit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what options to get: https://timdettmers.com/category/deep-learning/
  3. Use cloud computing - GCP, AWS, Azure, these services allow to rent computers on the cloud and access them

  For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, t do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Tue Mar 25 20:11:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

### For PyTorch since it is capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

e.g. Run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()


1

### Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])
# Or use
#tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###Moving tensors to back to the CPU

In [ ]:
# If tensor is on GPU, cann't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor above error with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Excercise and Rxtra curriculam. See exercises for this notebook here:
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises