<a href="https://colab.research.google.com/github/kamrulnannu/PyTorch-deep-learning/blob/main/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch


# Create random tensor
x_7_7 = torch.rand(7, 7)
print(x_7_7)

tensor([[3.6954e-01, 7.4285e-02, 6.8293e-01, 2.4589e-01, 6.8109e-01, 5.4075e-01,
         6.3960e-01],
        [4.9174e-01, 2.7745e-01, 4.4528e-01, 7.7612e-03, 7.4206e-01, 7.8885e-01,
         7.4710e-01],
        [6.2021e-01, 7.4111e-01, 1.7101e-01, 4.2442e-01, 2.7951e-01, 4.1074e-01,
         6.8446e-01],
        [7.1194e-01, 1.4337e-01, 5.5997e-01, 8.1320e-01, 8.2259e-02, 4.2883e-01,
         2.4325e-01],
        [2.3421e-01, 2.1637e-01, 9.6138e-01, 4.9540e-01, 4.3451e-01, 3.8408e-01,
         9.0492e-04],
        [9.9422e-01, 6.1293e-01, 5.8075e-01, 7.7206e-02, 5.6719e-01, 3.7926e-01,
         2.1552e-01],
        [3.1636e-01, 6.7526e-01, 2.0936e-01, 1.3145e-02, 3.5559e-01, 6.8848e-01,
         6.3794e-01]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
import torch
# Create another random tensor
x_1_7 = torch.rand(1, 7)
print(x_1_7)
x_7_1 = torch.transpose(x_1_7, 0, 1) # Transpose dim 0 and dim 1 to satisfy multiplication requirement
print(x_7_1)
# Perform matrix multiplication
x_mult = torch.matmul(x_7_7, x_7_1)
print(x_mult)

tensor([[0.4335, 0.0935, 0.8530, 0.4362, 0.1956, 0.8880, 0.7800]])
tensor([[0.4335],
        [0.0935],
        [0.8530],
        [0.4362],
        [0.1956],
        [0.8880],
        [0.7800]])
tensor([[1.9692],
        [2.0507],
        [1.6225],
        [1.7410],
        [1.5846],
        [1.6332],
        [1.5631]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
MANUAL_SEED = 0
#Create 2 tensors
torch.manual_seed(MANUAL_SEED)
x_7_7 = torch.rand(7, 7)
print(f"x_7_7: {x_7_7}")
torch.manual_seed(MANUAL_SEED)
x_1_7 = torch.rand(1, 7)
print(f"x_1_7: {x_1_7}")


# Matrix multiply tensors
x_7_1 = torch.transpose(x_1_7, 0, 1) # Transpose dim 0 and dim 1 to satisfy multiplication requirement
print(f"x_7_1: {x_7_1}")
x_mult = torch.matmul(x_7_7, x_7_1)
print(f"x_mult: {x_mult}, size: {x_mult.shape}")


x_7_7: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
x_1_7: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
x_7_1: tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])
x_mult: tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]), size: torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
